# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

encoding:       UTF-8

# Permalinks
permalink:      pretty
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

baseURL:            "https://dicthub.org"
repo:               "https://github.com/dicthub/dicthub.github.io"
current_version:    "1.0.1"

title:              DictHub
description:        "DictHub"
authors:            ""

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
